FROM python:3.10-slim
RUN apt-get update && \
    apt-get install -y sqlite3 libsqlite3-dev gcc && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY consumer.py .
COPY init_db.py .
RUN pip install confluent-kafka
RUN python init_db.py
CMD ["python", "consumer.py"]
