FROM python:3.11-slim

WORKDIR /app

COPY ../app/models.py ../app/dashboard.py ./

RUN pip install --no-cache-dir setuptools==78.1.1 fastapi uvicorn sqlalchemy psycopg2-binary

CMD ["uvicorn", "dashboard:app", "--host", "0.0.0.0", "--port", "8000"]
