FROM python:3.11-slim

WORKDIR /app

COPY ../app/models.py ../app/consumer.py ./

RUN pip install --no-cache-dir setuptools==78.1.1 sqlalchemy psycopg2-binary confluent-kafka tenacity

CMD ["python", "consumer.py"]
